### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by alxwrd** [RationalCoding/techno-synesthesia#1]
hello 👋!

I am getting the follow error on Firefox Quantum 58.0.2 (64-bit) on Windows 10.

```
SyntaxError: An invalid or illegal string was specified        bundle.js:3098
```

The page loads up, a request is made to access the webcam, the first frame of the webcam is displayed (actual image, not the pixelated version), then it stops.

Everything is working fine on Google Chrome on the same machine.

**Comment by t-mullen** [comment]
Firefox didn't like the ramping function I was using. Should be all fixed once gh-pages rebuilds. Thanks!
